version: 0.0
os: linux
files:
  - source: /Apv.AV.sln
    destination: /home/ec2-user/Apv.AV/
  - source: /Apv.AV.Common
    destination: /home/ec2-user/Apv.AV/Apv.AV.Common/
  - source: Apv.AV.Services.Data
    destination: /home/ec2-user/Apv.AV/Apv.AV.Services.Data
  - source: Apv.AV.Services
    destination: /home/ec2-user/Apv.AV/Apv.AV.Services
  - source: Apv.AV.Web
    destination: /home/ec2-user/Apv.AV/Apv.AV.Web
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restore_dotnet
      timeout: 300
      runas: root
    - location: scripts/build_dotnet
      timeout: 300
      runas: root
    - location: scripts/build_publish
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
