// <auto-generated />
using Apv.AV.Services.Data.FC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Apv.AV.Services.Data.Migrations
{
    [DbContext(typeof(ApvFCAppContext))]
    [Migration("20180206095902_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.AppVersion", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("downloadUrl");

                    b.Property<string>("features");

                    b.Property<bool>("forceUpgrade");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<decimal>("newVersionCode");

                    b.Property<string>("platform");

                    b.Property<decimal>("prevVersionCode");

                    b.HasKey("id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModel", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("carModelClassid");

                    b.Property<string>("carModelId");

                    b.Property<string>("coverImage");

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<string>("modelLabel");

                    b.Property<string>("modelLabelLoc");

                    b.Property<decimal>("order");

                    b.Property<bool>("published");

                    b.HasKey("id");

                    b.HasIndex("carModelClassid");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModelClass", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("companyId");

                    b.Property<string>("countryCode");

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<string>("modelClassBrand");

                    b.Property<string>("modelClassCode");

                    b.Property<string>("modelClassId");

                    b.Property<string>("modelClassLabel");

                    b.Property<string>("modelClassLabelLoc");

                    b.Property<string>("modelClassTypeLabel");

                    b.Property<string>("modelClassTypeLabelLoc");

                    b.Property<decimal>("order");

                    b.Property<bool>("published");

                    b.HasKey("id");

                    b.ToTable("CarModelClasses");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModelClassImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarModelClassid");

                    b.Property<string>("coverImage");

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<string>("onlineImage");

                    b.Property<string>("thumbnailImage");

                    b.Property<string>("verticalImage");

                    b.HasKey("id");

                    b.HasIndex("CarModelClassid");

                    b.ToTable("CarModelClassImage");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModelFinancialProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarModelid");

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<int?>("financialProductid");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.HasKey("id");

                    b.HasIndex("CarModelid");

                    b.HasIndex("financialProductid");

                    b.ToTable("CarModelFinancialProduct");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarPrice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("carModelid");

                    b.Property<string>("companyId");

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<decimal>("price");

                    b.HasKey("id");

                    b.HasIndex("carModelid");

                    b.ToTable("CarPrice");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.FinancialProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("description");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("FinancialProduct");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModel", b =>
                {
                    b.HasOne("Apv.AV.Services.Data.Models.FC.CarModelClass", "carModelClass")
                        .WithMany()
                        .HasForeignKey("carModelClassid");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModelClassImage", b =>
                {
                    b.HasOne("Apv.AV.Services.Data.Models.FC.CarModelClass", "CarModelClass")
                        .WithMany("CarModelClassImages")
                        .HasForeignKey("CarModelClassid");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarModelFinancialProduct", b =>
                {
                    b.HasOne("Apv.AV.Services.Data.Models.FC.CarModel")
                        .WithMany("financialProducts")
                        .HasForeignKey("CarModelid");

                    b.HasOne("Apv.AV.Services.Data.Models.FC.FinancialProduct", "financialProduct")
                        .WithMany()
                        .HasForeignKey("financialProductid");
                });

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.CarPrice", b =>
                {
                    b.HasOne("Apv.AV.Services.Data.Models.FC.CarModel", "carModel")
                        .WithMany("carPrices")
                        .HasForeignKey("carModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
