// <auto-generated />
using Apv.AV.Services.Data.FC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Apv.AV.Services.Data.Migrations
{
    [DbContext(typeof(ApvFCAppContext))]
    partial class ApvFCAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apv.AV.Services.Data.Models.FC.AppVersion", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("createdBy");

                    b.Property<DateTime>("createdDt");

                    b.Property<string>("downloadUrl");

                    b.Property<string>("features");

                    b.Property<bool>("forceUpgrade");

                    b.Property<string>("lastUpdatedBy");

                    b.Property<DateTime>("lastUpdatedDt");

                    b.Property<decimal>("newVersionCode");

                    b.Property<string>("platform");

                    b.Property<decimal>("prevVersionCode");

                    b.HasKey("id");

                    b.ToTable("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
